version: '3.9'

services:
  go-banking-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-banking-api
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASS: ${POSTGRESQL_PASS}
      POSTGRESQL_NAME: ${POSTGRESQL_NAME}
      POSTGRESQL_HOST: ${POSTGRESQL_HOST}
      POSTGRESQL_PORT: "${POSTGRESQL_PORT}"
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: "${SERVER_PORT}"
      JWT_SECRET: "${JWT_SECRET}"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - .:/app

  postgres:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - .env
    environment:
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASS: ${POSTGRES_PASS}
      POSTGRESQL_NAME: ${POSTGRESQL_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USER}"]
      interval: 10s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
